#!/bin/sh

. /reg/g/pcds/setup/pathmunge.sh
. /reg/g/pcds/setup/python.sh
pythondir=/reg/common/package/python/2.5.5
pathmunge $pythondir/bin
ldpathmunge $pythondir/lib

QTINC=/reg/neh/home/jbarrera/release/build/qt/include
QTLIB=/reg/neh/home/jbarrera/release/build/qt/lib/x86_64-linux-dbg

FFTINC=/reg/neh/home/jbarrera/fftw/include
FFTLIB=/reg/neh/home/jbarrera/fftw/lib

rm -f *.o
g++ -g -c ColorMap.cc || exit 1
g++ -g -c -I$FFTINC -I$QTINC Display.cc || exit 1
g++ -g -c -I$FFTINC RMatrix.cc || exit 1
g++ -g -c -I$FFTINC CMatrix.cc || exit 1
g++ -g -c -I$FFTINC jread.cc || exit 1
g++ -o jread *.o -g -L$QTLIB -L$FFTLIB -lrt -lQtGui -lQtCore -lfftw3 || exit 1
rm -f *.o

DATE=`date +%m.%d.%H.%M.%S`
mkdir versions/$DATE
cp -v j *.cc *.hh versions/$DATE

rm -f $HOME/valgrind.log
VALGRIND="valgrind --log-file=$HOME/valgrind.log --leak-check=full"
VALGRIND="valgrind --leak-check=full --track-origins=yes"
VALGRIND="valgrind -v --leak-check=yes"
VALGRIND=""

LD_LIBRARY_PATH="$LD_LIBRARY_PATH":$QTLIB

FILE=sid2.txt
FILE=

#gdb --args ./jread $FILE
#$VALGRIND ./jread $FILE
#$VALGRIND ./jread

./jread
# "$FILE"
